[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.37"
quinn = "0.11.7"
rcgen = "0.13.2"
rustls = "0.23.26"
tokio = {version = "1.44.2", features = ["full"] }
