[package]
name = "file-transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.37"
tokio = {version = "1.44.2", features = ["full"] }
quinn = {workspace = true}
quic-transport = {path = "../quic-transport"}
bytes = "1.10.1"
